language:
  ruby

rvm:
  - 2.7

services:
  - postgresql

before_script:
  - psql  -U postgres -c 'CREATE DATABASE bookmark_manager_test;'
  - psql  -U postgres bookmark_manager_test < db/migrations/01_create_bookmarks_table.sql
  - psql  -U postgres bookmark_manager_test < db/migrations/02_add_title_to_bookmarks.sql
  - psql  -U postgres bookmark_manager_test < db/migrations/03_create_comments_table.sql
  - psql  -U postgres bookmark_manager_test < db/migrations/04_create_tags_table.sql
  - psql  -U postgres bookmark_manager_test < db/migrations/05_create_bookmarks_tags_table.sql
  - psql  -U postgres bookmark_manager_test < db/migrations/06_create_users_table.sql

script:
  - bundle exec rspec
